### ISSUE TITLE
Check Github actions `run`

### ISSUE THREAD

**Issue by guettli** [foxundermoon/vs-shell-format#391]
It would be great if this extension could check Github Actions, too.

Example:

```yaml
runs:
  using: "composite"
  steps:
  - name: foo
    shell: bash
    run: |
      .... it would be great to see syntax errors via the shellformat vscode plugin.
```
